### ISSUE TITLE
ArgumentException: Invalid string value for yes/no property.

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.NET-lib-#10]
Lately I'm getting this error when stopping playback. Can't say exactly when this error started happening. I just updated to the latest version of MPV and the problem persists.

This occurs in MpvOnPropertyChange, case eofReachedUserData

eventProperty.DataString is null which is why it crashes.

	public static bool YesNoToBool(string yesNoString)
	{
		switch (yesNoString)
		{
			case "yes":
				return true;
			case "no":
				return false;
		}

		throw new ArgumentException("Invalid string value for yes/no property.");
	}

**Comment by hudec117** [comment]
Hello @mysteryx93,

Could you please confirm which version you updated to? Also, where you got the .dll from?

Currently the reason why DataString would be null is because the internal mpv format of the data was set to something other than "string" or no the pointer to the data was zero. Currently, I'm unable to replicate in the example app.

**Comment by mysteryx93** [comment]
Could it be this happens on audio files? It's happening all the time with my audio player and doesn't happen for you with video, this could be the reason.

**Comment by DaZiYuan** [comment]
![image](https://user-images.githubusercontent.com/80653/65165643-c7d07d80-da71-11e9-8fe1-69ec9fd6e88d.png)

it seems play video twice then call stop and dispose player can reporduce this issue.
not sure
```
player.Load("test.mp4");
player.Load("test.mp4");
player?.Stop();
player?.Dispose();
```

**Comment by mysteryx93** [comment]
Oh right I'm playing on loop!

**Comment by DaZiYuan** [comment]
I just reproduce it
```
        private void btnPlay_Click(object sender, RoutedEventArgs e)
        {
            player.Pause();
            player.Load(@"C:\Livewallpaper\0f29e29d-611f-4253-8b59-3f0c89ffe4dc\index.mp4");
            player.Resume();
        }

        private void btnDispose_Click(object sender, RoutedEventArgs e)
        {
            player.Stop();
            player.Dispose();
        }
```
you need click btn_play twice then click btn_dispose to reproduce this issue.
if just write in a method ,will not crashed.

https://github.com/DaZiYuan/Mpv.NET.lib/blob/master/src/Mpv.NET.WPFExample/MainWindow.xaml.cs

**Comment by sakib1361** [comment]
I can confirm that this issue can be reproduced, 
Load Media()
Pause/Stop
Load another Media()
Dispose()
=> After the media is loaded. You must wait till MediaLoaded fired. That's why sequencing code like @DaZiYuan mentioned in the second part wont crash. However, if a delay (await Task.Delay(3000)) is put after load, the system crashes saying the stated error.

**Comment by hudec117** [comment]
I am able to replicate this now, thank you for the sample repository @DaZiYuan.

The issue lies in the MpvPlayerHelper.YesNoToBool method (as you probably know), currently it's written so that any input which is not **specifically** "yes" or "no" will lead to an exception. Looking at it now, this is badly designed, I am simplifying it to a simple `return yesNoString == "yes";` This will ensure that if it is "yes" then it returns true, anything else can be considered falsy.

**Comment by mysteryx93** [comment]
When are you going to release an updated version with this fix?

**Comment by hudec117** [comment]
Release 1.1.1 now available: https://github.com/hudec117/Mpv.NET-lib-/releases/tag/v1.1.1
